name: .NET Desktop Build

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug
      additional_args:
        description: 'Additional build arguments (optional)'
        required: false
        type: string
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    env:
      Solution_Name: StringDecryptorBase.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Setup .NET Framework Developer Pack
      run: |
        choco install netfx-4.5.2-devpack -y

    # Add steps to explicitly install dnlib via NuGet
    - name: Create NuGet.Config
      run: |
        @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
          </packageSources>
        </configuration>
        "@ | Out-File NuGet.Config

    - name: Install dnlib Package
      run: |
        nuget install dnlib -Version 3.3.5 -OutputDirectory packages

    - name: Update Project References
      run: |
        $proj = Get-Content .\StringDecryptorBase\StringDecryptorBase.csproj
        $proj = $proj -replace '<Reference Include="dnlib" />', '<Reference Include="dnlib"><HintPath>..\packages\dnlib.3.3.5\lib\net45\dnlib.dll</HintPath></Reference>'
        $proj | Set-Content .\StringDecryptorBase\StringDecryptorBase.csproj

    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    - name: Build Solution
      run: |
        msbuild $env:Solution_Name /p:Configuration=${{ github.event.inputs.configuration || 'Release' }} /p:Platform="Any CPU" /m /p:RestorePackages=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: StringDecryptorBase-${{ github.event.inputs.configuration || 'Release' }}
        path: StringDecryptorBase\bin\${{ github.event.inputs.configuration || 'Release' }}
