name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    runs-on: windows-latest

    env:
      Solution_Name: StringDecryptorBase.sln
      Test_Project_Path: StringDecryptorBase.Tests\StringDecryptorBase.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --no-restore

    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --configuration ${{ matrix.configuration }} --no-build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: StringDecryptorBase-${{ matrix.configuration }}
        path: StringDecryptorBase\bin\${{ matrix.configuration }}
