name: .NET Desktop Build

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug
      additional_args:
        description: 'Additional build arguments (optional)'
        required: false
        type: string
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        include:
          - configuration: ${{ github.event.inputs.configuration || 'Release' }}
    
    runs-on: windows-2019  # Using windows-2019 which has better support for older .NET Framework versions

    env:
      Solution_Name: StringDecryptorBase.sln
      Test_Project_Path: StringDecryptorBase.Tests\StringDecryptorBase.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Add Windows SDK installation
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Setup .NET Framework Developer Pack
      run: |
        choco install netfx-4.5.2-devpack -y
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    - name: Build
      run: |
        $additionalArgs = "${{ github.event.inputs.additional_args }}"
        msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /m

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: StringDecryptorBase-${{ matrix.configuration }}
        path: StringDecryptorBase\bin\${{ matrix.configuration }}
